// productsData.js
const products = [
    {
        id: 1,
        name: "Redmi Note 12 Pro+ 5G",
        price: "₹26,490",
        description: "Redmi Note 12 Pro+ 5G is Xiaomi's latest mid-range smartphone offering in India. The top-of-the-line phone in the Note 12 series is a direct successor to the Redmi Note 11 Pro+ 5G (Review), which didn't quite pan out to be a segment leader as many would have hoped for, in our opinion. Xiaomi is now trying to fill the void with the Redmi Note 12 Pro+ 5G, with some segment-first hardware.",
        image: "https://i.gadgets360cdn.com/products/large/redmi-note-12-5g-pro-plus-db-gadgets360-800x600-1673019783.jpg?downsize=*:420&output-quality=80",
        category: "Electronics",
        rating: 4.5,
        brand: "Xiaomi",
        color: "Black",
        feature: "5G, AMOLED Display, 200MP Camera",
        available: true,
    },
    {
        id: 2,
        name: "Smartphone Tripod Stand",
        price: "₹2,944",
        description: "Portable and lightweight tripod stand for smartphones.",
        image: "https://m.media-amazon.com/images/I/61hWgalVmCL._AC_SL1500_.jpg",
        category: "Electronics",
        rating: 4.3,
        brand: "AmazonBasics",
        color: "Black",
        feature: "Adjustable Height, Lightweight",
        available: true,
    },
    {
        id: 3,
        name: "Fitness Tracker Watch",
        price: "$99",
        description: "Waterproof fitness tracker with heart rate and sleep monitor.",
        image: "https://th.bing.com/th/id/OIP.MvWBxT9dWU5kgeAFOq95HgHaIh?rs=1&pid=ImgDetMain",
        category: "Health & Fitness",
        rating: 4.0,
        brand: "Fitbit",
        color: "Black",
        feature: "Heart Rate Monitoring, Waterproof",
        available: true,
    },
    {
        id: 4,
        name: "Portable Power Bank 10000mAh",
        price: "$25",
        description: "Compact power bank with fast charging capabilities.",
        image: "https://m.media-amazon.com/images/I/51jlRU6J-AL.jpg",
        category: "Electronics",
        rating: 4.6,
        brand: "Anker",
        color: "White",
        feature: "Fast Charging, Compact",
        available: true,
    },
    {
        id: 5,
        name: "Wireless Mouse",
        price: "$19",
        description: "Ergonomic wireless mouse with adjustable DPI settings.",
        image: "https://th.bing.com/th?id=OIP.mCaTd09YN78H6MvVSiCN7wHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        category: "Computers",
        rating: 4.4,
        brand: "Logitech",
        color: "Gray",
        feature: "Adjustable DPI, Ergonomic Design",
        available: true,
    },
    {
        id: 6,
        name: "Stainless Steel Water Bottle",
        price: "$15",
        description: "Eco-friendly, insulated water bottle to keep drinks hot or cold.",
        image: "https://ridentkitchen.com/wp-content/uploads/2020/11/image-1.jpg",
        category: "Home & Kitchen",
        rating: 4.8,
        brand: "Hydro Flask",
        color: "Stainless Steel",
        feature: "Insulated, Eco-friendly",
        available: true,
    },
    {
        id: 7,
        name: "Laptop Backpack",
        price: "$45",
        description: "Water-resistant backpack with multiple compartments for laptops and accessories.",
        image: "https://th.bing.com/th/id/OIP.TUQ1IFBCNadUGfv_Q8OwjgHaHa?rs=1&pid=ImgDetMain",
        category: "Bags & Travel",
        rating: 4.5,
        brand: "Samsonite",
        color: "Gray",
        feature: "Water-resistant, Multiple Compartments",
        available: true,
    },
    {
        id: 8,
        name: "Noise Cancelling Earbuds",
        price: "$79",
        description: "Compact and lightweight earbuds with active noise cancellation.",
        image: "https://th.bing.com/th?id=OIP.JjK0owiAPucRt-i4rh0hXwHaGT&w=271&h=230&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        category: "Electronics",
        rating: 4.2,
        brand: "Sony",
        color: "White",
        feature: "Active Noise Cancellation, Compact",
        available: true,
    },
    {
        id: 9,
        name: "4K Action Camera",
        price: "$129",
        description: "Waterproof action camera with 4K video recording and Wi-Fi connectivity.",
        image: "https://th.bing.com/th?id=OIP._Q9SkkaaTJn3_dpXNChs2wHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        category: "Electronics",
        rating: 4.7,
        brand: "GoPro",
        color: "Black",
        feature: "4K Video, Waterproof",
        available: true,
    },
    {
        id: 10,
        name: "Rechargeable LED Flashlight",
        price: "$12",
        description: "High lumen LED flashlight with rechargeable battery and multiple modes.",
        image: "https://i5.walmartimages.com/asr/7db31195-ff4e-4f70-8f2a-92a3077d7b42.40d959d1abb97f3cb11a694bff854845.jpeg",
        category: "Outdoor & Sports",
        rating: 4.6,
        brand: "Maglite",
        color: "Black",
        feature: "Rechargeable, High Lumen",
        available: true,
    }
];

module.exports = products;
